name: Ola Mundo
on: push
jobs: 
 minha-tarefa:
    runs-on: ubuntu-latest
    steps:
      - name: Dizer ola
        run: echo "Alunas Sara e Heloisa."
      - name: Commit
        run: echo "Commit feito por ${{ github.actor }}"
